### ISSUE TITLE
Can't build on Debian 9.8

### ISSUE THREAD

**Issue by tank-trax** [rorywalsh/cabbage#43]
make

```
Compiling include_juce_audio_plugin_client_VST2.cpp
Compiling CabbagePluginEditor.cpp
Compiling CabbagePluginProcessor.cpp
Compiling CsoundPluginEditor.cpp
Compiling CsoundPluginProcessor.cpp
../../Source/Audio/Plugins/CsoundPluginProcessor.cpp: In member function ‘virtual void CsoundPluginProcessor::initAllCsoundChannels(juce::ValueTree)’:
../../Source/Audio/Plugins/CsoundPluginProcessor.cpp:172:25: error: ‘class Csound’ has no member named ‘SetStringChannel’; did you mean ‘GetStringChannel’?
                 csound->SetStringChannel (CabbageWidgetData::getStringProp (cabbageData.getChild (i), CabbageIdentifierIds::channel).getCharPointer(),
                         ^~~~~~~~~~~~~~~~
../../Source/Audio/Plugins/CsoundPluginProcessor.cpp:178:25: error: ‘class Csound’ has no member named ‘SetStringChannel’; did you mean ‘GetStringChannel’?
                 csound->SetStringChannel (CabbageWidgetData::getStringProp (cabbageData.getChild (i), CabbageIdentifierIds::channel).getCharPointer(),
                         ^~~~~~~~~~~~~~~~
../../Source/Audio/Plugins/CsoundPluginProcessor.cpp:229:13: error: ‘class Csound’ has no member named ‘SetStringChannel’; did you mean ‘GetStringChannel’?
     csound->SetStringChannel ("LAST_FILE_DROPPED", "");
             ^~~~~~~~~~~~~~~~
Makefile:187: recipe for target 'build/intermediate/Debug/CsoundPluginProcessor_dc39856c.o' failed
make: *** [build/intermediate/Debug/CsoundPluginProcessor_dc39856c.o] Error 1
```

**Comment by tank-trax** [comment]
./buildCabbage gives these errors

```
Compiling GenericCabbagePluginProcessor.cpp
MakePluginEffect:183: recipe for target 'build/intermediate/Release/CsoundPluginProcessor_dc39856c.o' failed
make: *** [build/intermediate/Release/CsoundPluginProcessor_dc39856c.o] Error 1
make: *** Waiting for unfinished jobs....
cp: cannot stat './build/CabbagePlugin.so': No such file or directory
JUCE v5.3.2

```

```
Compiling CabbageSettingsWindow.cpp
MakeCabbageLite:194: recipe for target 'build/intermediate/Release/CsoundPluginProcessor_dc39856c.o' failed
make: *** [build/intermediate/Release/CsoundPluginProcessor_dc39856c.o] Error 1
make: *** Waiting for unfinished jobs....
cp: cannot stat './build/CabbageLite': No such file or directory

```

**Comment by rorywalsh** [comment]
Can you build from the develop branch?

**Comment by tank-trax** [comment]
Yes. Same thing

cp: cannot stat './build/CabbagePlugin.so': No such file or directory

**Comment by rorywalsh** [comment]
You must be using an old version of Csound. Can you update? I think this [method ]( 
https://github.com/csound/csound/blob/develop/include/csound.hpp#L760-L763)was added sometime around 6.11?

**Comment by tank-trax** [comment]
I have Csound in /usr/bin /usr/lib /usr/include and it's the version that comes with Debian 
added the latest to /usr/local/bin /usr/local/include /usr/local/lib and it looks to be building but only when I run python configureMakefiles.py and then make
./buildCabbage still fails

**Comment by tank-trax** [comment]
it got as far as 

```
Linking CabbageLite - App
Copying over docs and icons…
/tmp/ccZURfoa.o: In function `Csound::GetInputName()':
testCsoundFile.cpp:(.text._ZN6Csound12GetInputNameEv[_ZN6Csound12GetInputNameEv]+0x18): undefined reference to `csoundGetInputName'
collect2: error: ld returned 1 exit status
cp: cannot stat 'testCsoundFile': No such file or directory

```

**Comment by rorywalsh** [comment]
Can you comment out this line:
https://github.com/rorywalsh/cabbage/blob/master/Builds/LinuxMakefile/buildCabbage#L85
Of modify the paths so that it finds the newest Csound? It's not critical that this builds so simply commenting it out should do the trick.

**Comment by tank-trax** [comment]
I tried again and ./buildCabbage has same error 

`cp: cannot stat './build/CabbagePlugin.so': No such file or directory`

make will finish with 
```
Linking CabbagePlugin - Shared Code
Linking CabbagePlugin - VST
```
and builds only 
`CabbagePlugin.a` and `CabbagePlugin.so`

**Comment by tank-trax** [comment]
it's still only building CabbageLite

**Comment by tank-trax** [comment]
for some reason the git clone version would only build CabbageLite even after numerous deletions and attempts 

I downloaded the cabbage-2.0.03.zip packed and that managed to build everything with lines 85 and 86 commented out from buildCabbage 

thank you for your timely replies
